### ISSUE TITLE
Requirement 3 - Clinker Services Dictionary

### ISSUE THREAD

**Issue by ConnorSullivan10** [ConnorSullivan10/ClinkedIn-ZackTaylor#3]
# User Story
As a ClinkedIn member, I want to list my services so that other inmates can ask me for help.

# AC
*When* a user joins ClinkedIn
*And* they view another users profile
*Then* they should be able to see any services that the other user offers
*And* they should be able to request a service
*If* they are already friends *and* not enemies

# Dev Notes
* Each User Profile (as referenced in #1) should contain a collection of Services
* Create method in ClinkedIn Repository to add services to the user's account. Should look similar to:
```
 public void addServiceToClinker (Clinker selectedClinker, string skill) 
{
    selectedClinker.Services.Add(new LineItem{skill, false});
}
```

* Create method to request service from another user:

```
public void requestService(Clinker serviceClinker, string service)
{
   // Service.service should reference that the string inside the LineItem matches the inputted string
    var selectedService = serviceClinker.Services.FirstOrDefault(Service.service);
   //Below code should access the matching service from the selected service, and change it's 
   isRequested value to true
   serviceClinker.Services.selectedService.isRequested = true;
}
```

**Comment by gseals** [comment]
update?
[HttpPut("{id}")]
public IActionResult UpdateClinker(int id)
{
}
